name: docker.yml
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  build:
    strategy:
      matrix:
        apps: [ { name: privio/api, file: ./apps/api/Dockerfile }, { name: privio/web, file: ./apps/web/Dockerfile } ]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.apps.name }}
      - name: "Build and push"
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.apps.file }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}